### ISSUE TITLE
Add AdminLTE & Create Dashboard UI

### ISSUE THREAD

**Issue by Hashadhi** [Hashadhi/pos-frontend#2]

**Comment by Hashadhi** [comment]
Create Navigation UI
Dashboard (Tot customers, Tot items, tot orders, tot income

**Comment by Hashadhi** [comment]
@ThakshilaNuwangi This may take 40 mnts

**Comment by BhashithaArambepola** [comment]
@ThakshilaNuwangi this may take 45min

**Comment by ThakshilaNuwangi** [comment]
This may take 45 mnts

**Comment by ShakyaP94** [comment]
45minits
